services:
  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq-example
    restart: always
    ports:
      - "5673:5672" # port for AMQP
      - "15673:15672" # port for RabbitMQ management
    #    environment:
    # RABBITMQ_DEFAULT_USER: user
    # RABBITMQ_DEFAULT_PASS: password
    # RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit load_definitions \"/etc/rabbitmq/definitions.json\"" # Load definitions from file
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      # - ./definitions.json:/etc/rabbitmq/definitions.json # Automatically load definitions from file
    networks:
      - rabbitmq_network

volumes:
  rabbitmq_data:
    driver: local

networks:
  rabbitmq_network:
    driver: bridge
